import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../../node_modules/bootstrap/dist/css/bootstrap.css'
import '../../node_modules/font-awesome/css/font-awesome.min.css'
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "clone amazon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}

      >
        <div className="c1">
          <Link href={'./'}>
            <div className="imf"></div>

          </Link>
          <div className="text1">
            <div className="ico"></div>
            <h6>Delivering to Indore 452001</h6>
            <h5>Update location</h5>
          </div>
          <div className="sarbar">
            <div className="s1">
              <select name="" id="">
                <option value="">
                  all
                </option>
              </select>
            </div>
            <div className="s2">
              <form action="">
                <input type="search" placeholder='Search Amazon,in' />
              </form>
            </div>
            <div className="s3">
              <div className="saricon"></div>
            </div>
          </div>
          <div className="en">
            <div className="ic"></div>
            <select name="" id="">
              <option value="">
                en
              </option>
            </select>
          </div>
          <div className="text1">
            <h6>hello,sign in</h6>

            <select name="" id="">
              <option value="">
                <h5>account & list</h5>
              </option>
            </select>
          </div>

          <div className="text1">
            <h6>returns</h6>
            <h5>& orders</h5></div>
          <div className="cart">
            <div className="box"></div>
            <div className="gra">
              cart
            </div>
          </div>
        </div>

        {children}

      </body>
    </html>
  );
}
